mainLore: "§c§l§m  §6§l§m  §e§l§m  §a§l§m  §b§l§m  §e§l装备淬炼§b§l§m  §a§l§m  §e§l§m  §6§l§m  §c§l§m  "
speStoneLore: "§c§l§m  §6§l§m  §e§l§m  §a§l§m  §b§l§m  §e§l宝石镶嵌§b§l§m  §a§l§m  §e§l§m  §6§l§m  §c§l§m  "
# 是否开启物品名+几的等级信息
# 由于高版本和低版本许多武器装备材料名不一致
# 使用前请先前往chinesename.yml修改材料名或自己添加材料名和名字
# 目前的chinesename.yml是1.12.2版本
DisplayNameInfo:
  enabled: false
  suffix: "§a§l+{level}" # 物品名后缀,{level}为淬炼等级
# 淬炼到达多少星时触发全服播报
broadcastlevel: 6
settings:
  enablescript: true
  # 淬炼、宝石镶嵌、保护符镶嵌、精魂镶嵌后的lore顺序
  SortOrder:
    - "{lore}"
    - "{refinement}"
    - "{spestone}"
    - "{paper}"
    - "{soul}"
  JoinMessage:
    1:
      permission: "karrefinement.joinmessage.1"
      #支持placeholderapi
      msg:
        - "§c§l§m  §6§l§m  §e§l§m  §a§l§m  §b§l§m  §e§l欢迎消息§b§l§m  §a§l§m  §e§l§m  §6§l§m  §c§l§m  "
        - "§c§l尊贵的一星套装拥有者{player}加入了游戏!"
        - "§c§l§m  §6§l§m  §e§l§m  §a§l§m  §b§l§m  §e§l欢迎消息§b§l§m  §a§l§m  §e§l§m  §6§l§m  §c§l§m  "
    15:
      permission: "karrefinement.joinmessage.15"
      #支持placeholderapi
      msg:
        - "§c§l§m  §6§l§m  §e§l§m  §a§l§m  §b§l§m  §e§l欢迎消息§b§l§m  §a§l§m  §e§l§m  §6§l§m  §c§l§m  "
        - "§c§l尊贵的十五星套装拥有者{player}加入了游戏!"
        - "§c§l§m  §6§l§m  §e§l§m  §a§l§m  §b§l§m  §e§l欢迎消息§b§l§m  §a§l§m  §e§l§m  §6§l§m  §c§l§m  "
  data:
    # 数据存储方式：SQLite或MySQL
    storage: SQLite
    MySQL:
      # 数据库主机地址
      Host: '127.0.0.1'
      # 数据库端口号
      Port: '3306'
      # 数据库用户名
      Username: 'root'
      # 数据库密码
      Password: '1234'
      # 数据库名称
      Database: 'minecraft'
      # 数据库连接参数
      Parameters: 'useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC'

      Pool:
        # 最大连接池大小
        MaximumPoolSize: 20
        # 最小空闲连接数
        MinimumIdle: 5
        # 单个连接的最大生命周期（毫秒）
        MaxLifetime: 1800000
        # 连接超时时间（毫秒）
        ConnectionTimeout: 3000
        # 空闲连接的超时时间（毫秒）
        IdleTimeout: 6000
