#主lore中必须包含"装备淬炼"这四个字
mainLore: "§c§l§m  §6§l§m  §e§l§m  §a§l§m  §b§l§m  §e§l装备淬炼§b§l§m  §a§l§m  §e§l§m  §6§l§m  §c§l§m  "
speStoneLore: "§c§l§m  §6§l§m  §e§l§m  §a§l§m  §b§l§m  §e§l宝石镶嵌§b§l§m  §a§l§m  §e§l§m  §6§l§m  §c§l§m  "