name: KarRefinement
main: vip.mcsj.www.karrefinement.main.KarRefinement
version: 2.0.1.0-beta
author: Karounac58
api-version: 1.13
commands:
  karrefinement:
    aliases:
      - "krf"
depend:
  - NBTAPI
  - PlaceholderAPI
  - Vault
softdepend: [AttributePlus,SX-Attribute,CraneAttribute]